# Retrieve the latest logs by SSH-ing to server

# load server env variables
serverID <- Sys.getenv("SERVER_ID")
serverIP <- Sys.getenv("SERVER_IP")
serverPW <- Sys.getenv("SERVER_PW")
serverPW2 <- Sys.getenv("SERVER_PW2")
# pathEMu <- Sys.getenv("EMU_DIR")
pathFiler <- Sys.getenv("FILER_DIR")

# load local enviro variables
origdir <- getwd()
locEMu <- Sys.getenv("EMU_LOC")
locFiler <- Sys.getenv("FILER_LOC")

# # Uncomment this if testing on test-server
# pathEMu <- Sys.getenv("EMU_DIR_BOO") # "data/eaudit/"
# pathFiler <- Sys.getenv("FILER_DIR_BOO") # "data/filer/"

# # Uncomment this if testing locally
# pathEMu <- Sys.getenv("EMU_LOC")
# pathFiler <- Sys.getenv("FILER_LOC")


# Create local directories for audit logs
# if (dir.exists(paste0(origdir, locEMu)) == FALSE) {
#   dir.create(paste0(origdir, locEMu))
# }

if (dir.exists(paste0(origdir, locFiler)) == FALSE) {
  dir.create(paste0(origdir, locFiler))
}


# get data from server if running on the server

session <- ssh_connect(host = paste0(serverID, "@", serverIP),
                       passwd = serverPW,
                       verbose = 2)

## Get most recent EMu audit log
##  NOTE:
##   EMu audit logs are generated by a periodic export
##    - Mon EMu audit log represents Fri+Sat+Sun activity
##    - Tue-Fri EMu audit logs represent the previous day's activity


# get_latest_raw <- ssh_exec_internal(
#   session = session, 
#   command = paste("cd", pathEMu, "&&",
#                   "ls -td -- */ | head -n 1"))
# 
# get_latest <- gsub("\n", "", rawToChar(get_latest_raw$stdout))
# 
# scp_download(session,
#              # pathEMu
#              paste0(pathEMu, get_latest),
#              # '"$(ls ', pathEMu,
#              # ' -1t --color=never | head -1)"'),
#              to = paste0(origdir,locEMu))

# Get most recent Filer audit log with corresponding EMu log
## NOTE:
##  Filer logs run continuously & close out at end of the day
##    - On Mon, get the Friday & Saturday filer logs  [update: "get Fri log"]
##    - On Tue-Fri, get the previous day's logs [update: Tues = get Sat/Sun/Mon; W-F = prev day]
##  Note:  No log is generated if there are no file additions/edits/deletions

# # filerDF <- list.dirs("data/", pattern = "audit", full.names = T)
# # 
  
filerDate <- gsub("-","",(Sys.Date() - 1))

command <- paste0('echo "" | sudo -s -S su root')

# ssh_exec_internal(
#   session = session,
#   command = paste0('echo "', serverPW2,
#                    '\n" | sudo -S su root'))

scp_download(session, 
             paste0(pathFiler, 
                    filerDate),
             to = paste0(origdir,locFiler))

if (format(Sys.Date(), "%a") == "Mon") {
  for (i in 2:3) {

    filerDateMon <- gsub("-", "", (Sys.Date() - i))
    scp_download(session,
                 paste0(pathFiler,
                        filerDateMon),
                 to = paste0(origdir,locFiler))
  }

}

Sys.sleep(2)

ssh_disconnect(session)

Sys.sleep(2)

# # output of this script should be:
# dataEMu <- "RENVIRON-VAR-path-to/latest/EMuLog.csv/xml"
# dataFiler <-  "RENVIRON-VAR-path-to/latest/FilerLog.csv"
