# Retrieve the latest logs by SSH-ing to server

# load enviro variables
origdir <- getwd()
pathEMu <- Sys.getenv("EMU_DIR")
pathFiler <- Sys.getenv("FILER_DIR")
locEMu <- Sys.getenv("EMU_LOC")
locFiler <- Sys.getenv("FILER_LOC")

# # Uncomment this if testing on test-server
# pathEMu <- Sys.getenv("EMU_DIR_BOO") # "data/eaudit/"
# pathFiler <- Sys.getenv("FILER_DIR_BOO") # "data/filer/"


# Create local directories for audit logs
if (!dir.exists(paste0(origdir, locEMu))) {
  dir.create(paste(locEMu))
}

if (!dir.exists(paste0(origdir, locFiler))) {
  dir.create(paste(locFiler))
}


# get data from server if running on the server

session <- ssh_connect(host = paste0(serverID, "@", serverIP),
                       verbose = 2)

# ADD FORMULA FOR PULLING MOST RECENT
# OTHERWISE - prompt for date

# # 'cd' doesn't seem to actually change the pwd within the ssh functions:
# emu_dir <- ssh_exec_wait(session,
#                          command = paste0('cd ', pathTest, # pathEMu,
#                                           '"$(ls ', pathTest, # pathEMu,
#                                           ' -1t --color=never | head -1)"'
#                          ))
#                          # command = 'cd "$(\ls -1dt ./*/ | head -n 1)"')

## Get most recent EMu audit log
##  NOTE:
##   EMu audit logs are generated by a periodic export
##    - Mon EMu audit log represents Fri+Sat+Sun activity
##    - Tue-Fri EMu audit logs represent the previous day's activity


scp_download(session, 
             paste0(pathEMu,
                    '"$(ls ', pathEMu,
                    ' -1t --color=never | head -1)"'),
             to = paste0(origdir,locEMu))


# Get most recent Filer audit log with corresponding EMu log
## NOTE:
##  Filer logs run continuously & close out at end of the day
##    - On Mon, get the Friday & Saturday filer logs (No Sunday filer log?)
##    - On Tue-Fri, get the previous day's logs

# # filerDF <- list.dirs("data/", pattern = "audit", full.names = T)
# # 
  
filerDate <- gsub("-","",(Sys.Date()-1))
scp_download(session, 
             paste0(pathFiler, 
                    filerDate),
             to = paste0(origdir,locFiler))

if (format(Sys.Date(), "%a") == "Mon") {
  for (i in 2:3) {

    filerDate <- gsub("-","",(Sys.Date()-i))
    scp_download(session,
                 paste0(pathFiler,
                        filerDate),
                 to = paste0(origdir,locFiler))
  }

}

Sys.sleep(2)

ssh_disconnect(session)

Sys.sleep(2)

# # output of this script should be:
# dataEMu <- "RENVIRON-VAR-path-to/latest/EMuLog.csv/xml"
# dataFiler <-  "RENVIRON-VAR-path-to/latest/FilerLog.csv"
