# Import the latest logs to R
#
# Import log of EMu records modified on previous day ####
# # background & alternatives here:
# # https://stackoverflow.com/questions/33446888/r-convert-xml-data-to-data-frame

## NOTE:
## pathEMu & pathFiler are defined in 050checkRenv.R and .Renviron

## Get most recent EMu audit log
##  NOTE:
##   EMu audit logs are generated by a periodic export
##    - Tues-Fri EMu audit logs represent the previous day's activity
##    - Mon EMu audit log represents Fri+Sat+Sun activity <-- TESTING THIS

# timeEMu <- file.info(list.files(paste(pathEMu), full.names = T))
timeEMu <- file.info(list.files(paste0(origdir, locEMu), full.names = T))

# dfEMu <- list.dirs(paste(pathEMu), full.names = T)
dfEMu <- list.dirs(paste0(origdir, locEMu), full.names = T)


if (NROW(list.dirs(paste0(origdir, locEMu))) < 2) {
  
  print(paste("no EMu audit log for", filerDate))
  write.table(print(paste("No EMu log for", filerDate)), 
              file = paste0("EMuauditErrorlog_",filerDate,".txt"))
  
} else {
  emu1 <- read.csv(paste0(dfEMu[NROW(dfEMu)], "/",
                          list.files(dfEMu[NROW(dfEMu)], pattern = "eaudit")),
                   # rownames(dfEMu)[which.max(dfEMu$ctime)],
                   stringsAsFactors = F)

  emu2 <- read.csv(paste0(dfEMu[NROW(dfEMu)], "/",
                          list.files(dfEMu[NROW(dfEMu)], pattern = "Group1")),
                   # rownames(dfEMu)[which.max(dfEMu$ctime)],
                   stringsAsFactors = F)

}

# Get most recent Filer audit log with corresponding EMu log
dfFiler <- list.dirs(paste0(origdir, locFiler), full.names = T)

if (!dir.exists(paste0(origdir, locFiler, filerDate))) {
  
  print(paste("no filer audit log for", filerDate))
  # write.table(print(paste("No Filer log for", filerDate)), 
  #             file = paste0("auditErrorlog_",filerDate,".txt"))
  filerBU <- data.frame("timestamp.UTC." = character(),        
                        "category" =  character(),
                        "event.type" =  character(),
                        "path.from" =  character(),
                        "new.path.to" = logical(),
                        "user" = integer(),
                        "group" = integer(),
                        "sid" = integer(),
                        "share.export.name" = logical(),
                        "volume.type" =  character(),
                        "client.IP" = logical(),
                        "snapshot.timestamp.UTC." = logical(),
                        "shared.link" = logical(),
                        stringsAsFactors = F)
  
} else {

    filerBU <- read.csv(paste0(dfFiler[NROW(dfFiler)], "/",
                             list.files(dfFiler[NROW(dfFiler)], pattern = "audit")),
                      stringsAsFactors = F)
}


# On Mondays, get Friday & Saturday logs, too
if (format(max(timeEMu$ctime), "%a") == "Mon") {
  for (i in 1:2) {
    filerDateMon <- gsub("-","",(Sys.Date()-(1+i)))
    if (!dir.exists(paste0(origdir, locFiler, filerDateMon))) {
      
      print(paste("no filer audit log for", (filerDateMon)))
      
      filerTMP <- data.frame("timestamp.UTC." = character(),        
                             "category" =  character(),
                             "event.type" =  character(),
                             "path.from" =  character(),
                             "new.path.to" = logical(),
                             "user" = integer(),
                             "group" = integer(),
                             "sid" = integer(),
                             "share.export.name" = logical(),
                             "volume.type" =  character(),
                             "client.IP" = logical(),
                             "snapshot.timestamp.UTC." = logical(),
                             "shared.link" = logical(),
                             stringsAsFactors = F)
      
    } else {
      
      filerTMP <- read.csv(paste0(dfFiler[NROW(dfFiler)-i], "/",
                                  list.files(dfFiler[NROW(dfFiler)-i], pattern = "audit")),
                           stringsAsFactors = F)
    }

    filerBU <- rbind(filerBU, filerTMP)
  }
}
